services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: guge
      POSTGRES_PASSWORD: guge
      POSTGRES_DB: guge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
